// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'constants.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_single_bytes`, `process_single_file`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Result < Vec < u8 > , String >>>
abstract class ResultVecU8String implements RustOpaqueInterface {}

class BatchImageCompress {
  const BatchImageCompress();

  static Future<List<ResultVecU8String>> bytes(
          {required List<Uint8List> bytesList,
          CompressFormat? compressFormat,
          int? maxWidth,
          int? maxHeight,
          int? quality,
          FilterType? samplingFilter,
          int? speed}) =>
      NativeImageCompress.instance.api.crateApiBatchBatchImageCompressBytes(
          bytesList: bytesList,
          compressFormat: compressFormat,
          maxWidth: maxWidth,
          maxHeight: maxHeight,
          quality: quality,
          samplingFilter: samplingFilter,
          speed: speed);

  static Future<List<ResultVecU8String>> filePaths(
          {required List<String> filePaths,
          CompressFormat? compressFormat,
          int? maxWidth,
          int? maxHeight,
          int? quality,
          FilterType? samplingFilter,
          int? speed}) =>
      NativeImageCompress.instance.api.crateApiBatchBatchImageCompressFilePaths(
          filePaths: filePaths,
          compressFormat: compressFormat,
          maxWidth: maxWidth,
          maxHeight: maxHeight,
          quality: quality,
          samplingFilter: samplingFilter,
          speed: speed);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchImageCompress && runtimeType == other.runtimeType;
}
